title: LeXurey
theme: jekyll-theme-minimal
description: >-
 ## 👥 Who We Are

### Pei Xu – Founder & CEO  
[LinkedIn](https://www.linkedin.com/in/talbenxu/)  
Visionary in enterprise blockchain and smart contract security. Leads LeXurey’s product direction with expertise in ERP transformation and privacy-preserving compliance.

### Joe Cardinale – ERP Senior Advisor  
[LinkedIn](https://www.linkedin.com/in/joecardinale/)  
Decades of experience guiding ERP rollouts in complex industries. Advises LeXurey on architecture, delivery models, and industry partnerships.

### Dr. Yuekang Li – Web3 Security Advisor  
[LinkedIn](https://www.linkedin.com/in/yuekang-li-9a890b68/)  
Lecture at UNSW and expert in formal verification and fuzz testing. Leads the research behind LeXurey's smart contract assurance pipeline.

### Yang Yu – Chief Operating Officer  
[LinkedIn](https://www.linkedin.com/in/brandon-yang-yu/)  
Responsible for solution delivery and systems engineering. Oversees cross-platform implementation and client satisfaction.

### Ziqi Ding – Security Researcher  
[LinkedIn](https://www.linkedin.com/in/ziqi-ding-38353a327/)  
Focuses on source mapping and vulnerability detection in smart contracts. Builds the tooling for profit-centric fuzzing and compliance auditing.
show_downloads: false
